### PR TITLE
Weapon Inventory pick & drop System

### LINKED ISSUE #58: Implement Weapon Integration with Existing Inventory System
This issue will be worked on in Unity by navigating to the following path: Project > Assets > Scenes > DemoPrincipalScene. The weapon model to be implemented can be found in Assets > PolygonSciFiCity > Prefabs > Weapons. 

Issue implementacion arma

The inventory system currently in use is the Devion Games Inventory System, which has predefined mechanics for managing items in the game. Documentation and video tutorials for the inventory system can be found here: [Devion Games Inventory System Tutorials]
https://www.youtube.com/@Zerano100/videos

### **Weapon Selection and Setup:**

Choose one of the weapon models available in PolygonSciFiCity > Prefabs > Weapons for integration. Ensure the model is optimized for use with the character.

Captura de pantalla 2024-11-20 214940

Set up the weapon as a pickable object in Unity, ensuring it is interactable by the player.

### **Inventory Integration:**

Add the weapon as an item in the Devion Games Inventory System, with appropriate metadata such as:

Item Name: (e.g., "SciFi Rifle").
Icon: Generate or use an icon that visually represents the weapon.
Description: (e.g., "A futuristic rifle designed for advanced combat").
Item Type: Weapon.
Ensure the weapon can be:
Picked up from the ground using the interaction key F.
Stored in the inventory as an individual item.
Dropped back into the game world from the inventory.
Equipping the Weapon:

### **Implement logic to equip the weapon to the active character.**
Position the weapon in the character's hand when equipped, ensuring proper alignment and orientation.
Configure animations (if available) or placeholders to simulate holding the weapon.
Interaction Logic:

The weapon should be interactable when dropped in the environment, allowing the player to pick it up again.
Use Unity's Collider and Rigidbody components to enable physical interaction.

The goal of this issue is to integrate a weapon into the existing inventory system, allowing players to interact with it naturally (pick up, store, equip, and drop). This feature will enhance gameplay by providing dynamic interactions and aligning with the futuristic, cyberpunk aesthetic of Citizen of Arcanis.

### **Acceptance Criteria:**

The player can pick up the weapon using the F key.
The weapon is stored in the inventory with an appropriate icon and metadata.
The player can equip the weapon, which appears in the character's hand when selected.
The weapon can be dropped from the inventory, becoming an interactable object in the game world.

### **How to Apply**
Follow the [README](https://github.com/SunsetLabs-Game/Citizen-of-Arcanis-FrontEnd/blob/main/README.md)
 outlined in the README file.
If you have any questions or need assistance along the way, feel free to tag me at @sebas11042 🚀🔥
We can’t wait to see your magic in action! 😎✨

### PR DESCRIPTION
**Pull request by od-hunter**
Resolves #58 
I have created the pick & drop system for the scifi gun riffle, please new changes were made in the DemoPricipalScene #58 to avoid merge conflicts.

For subsequent weapons, after creating the devion item attached the weapon manager scripts to the prefab as well as rigid body and colliders.

For subsequent characters, add players weapon handler scripts, use robot01 clone as reference copy its animator rigs object and weapon spawner object.

Other informations are included in scripts comment.

@Josue19-08 , please review

### CODE REVIEW

**Comment by Josue19-08** [comment]
@od-hunter  Ok, please add a video demonstration of the work done. Please show in the video how you execute the project and how you perform the tests.

**Comment by od-hunter** [comment]
https://github.com/user-attachments/assets/2675d07b-12c1-44de-aff0-d83a86473baa

**Comment by od-hunter** [comment]
https://github.com/user-attachments/assets/1e7ffd9b-af05-49ee-b895-68cdfcd1ce3a

**Comment by od-hunter** [comment]
https://github.com/user-attachments/assets/8ec96d00-0278-4b3d-bc34-9b706ec03530

**Comment by od-hunter** [comment]
https://github.com/user-attachments/assets/517dd19d-f0e7-4866-8e1d-4474534bccec

**Comment by od-hunter** [comment]
Pardon me, I had to break the video into parts because I couldn’t send a video that exceeds 10mb at once.

**Comment by od-hunter** [comment]
*Setting Up the System*

To integrate the new item into the system, follow these steps:

1. *Register the Item*: After creating a new item, ensure it is registered in the database.
2. *Add Weapon Manager Component*: Attach the Weapon Manager component to the prefab created for the new item. This will enable the item to interact with the system.

*Configuring the Weapon Prefab*

For optimal positioning and realism:

1. *Copy and Paste Transforms and Physics*: Duplicate the transforms and physics from the Sci-Fi Gun prefab and paste them into your new weapon prefab. Adjust as needed to achieve a realistic equipping look.

*Configuring the Player*

To enable weapon handling and rigging:

1. *Add Player Weapon Handler and Rig Builder Components*: Attach both components to your player game object.
2. *Copy and Paste Animation Rigs and Weapon Spawner*: Duplicate the animation rigs and weapon spawner from the Robot Clone prefab and paste them into your new player. Adjust the rigs' transforms to your preference.

*Configuring the Inventory Window*

To display the inventory window correctly:

1. *Input Inventory Window Name*: Enter the name of the inventory window ("Inventory") in the corresponding string field.

*Enabling UI Interactions*

To control UI buttons and enable equipping and dragging:

1. *Add Slot Weapon Manager Component*: Attach this component to the UI Weapon Slot. This will integrate the Devion Inventory System with Unity UI, physics, and animation rigging, allowing for seamless weapon interactions.

With these steps completed, you can now run the system and enjoy quick and easy weapon interactions.

@Josue19-08

**Pull request closed without merging**
