### PR TITLE
Implement Weapon Inventory System feature

### LINKED ISSUE #58: Implement Weapon Integration with Existing Inventory System
This issue will be worked on in Unity by navigating to the following path: Project > Assets > Scenes > DemoPrincipalScene. The weapon model to be implemented can be found in Assets > PolygonSciFiCity > Prefabs > Weapons. 

Issue implementacion arma

The inventory system currently in use is the Devion Games Inventory System, which has predefined mechanics for managing items in the game. Documentation and video tutorials for the inventory system can be found here: [Devion Games Inventory System Tutorials]
https://www.youtube.com/@Zerano100/videos

### **Weapon Selection and Setup:**

Choose one of the weapon models available in PolygonSciFiCity > Prefabs > Weapons for integration. Ensure the model is optimized for use with the character.

Captura de pantalla 2024-11-20 214940

Set up the weapon as a pickable object in Unity, ensuring it is interactable by the player.

### **Inventory Integration:**

Add the weapon as an item in the Devion Games Inventory System, with appropriate metadata such as:

Item Name: (e.g., "SciFi Rifle").
Icon: Generate or use an icon that visually represents the weapon.
Description: (e.g., "A futuristic rifle designed for advanced combat").
Item Type: Weapon.
Ensure the weapon can be:
Picked up from the ground using the interaction key F.
Stored in the inventory as an individual item.
Dropped back into the game world from the inventory.
Equipping the Weapon:

### **Implement logic to equip the weapon to the active character.**
Position the weapon in the character's hand when equipped, ensuring proper alignment and orientation.
Configure animations (if available) or placeholders to simulate holding the weapon.
Interaction Logic:

The weapon should be interactable when dropped in the environment, allowing the player to pick it up again.
Use Unity's Collider and Rigidbody components to enable physical interaction.

The goal of this issue is to integrate a weapon into the existing inventory system, allowing players to interact with it naturally (pick up, store, equip, and drop). This feature will enhance gameplay by providing dynamic interactions and aligning with the futuristic, cyberpunk aesthetic of Citizen of Arcanis.

### **Acceptance Criteria:**

The player can pick up the weapon using the F key.
The weapon is stored in the inventory with an appropriate icon and metadata.
The player can equip the weapon, which appears in the character's hand when selected.
The weapon can be dropped from the inventory, becoming an interactable object in the game world.

### **How to Apply**
Follow the [README](https://github.com/SunsetLabs-Game/Citizen-of-Arcanis-FrontEnd/blob/main/README.md)
 outlined in the README file.
If you have any questions or need assistance along the way, feel free to tag me at @sebas11042 🚀🔥
We can’t wait to see your magic in action! 😎✨

### PR DESCRIPTION
**Pull request by od-hunter**
Resolves #58 
This update introduces the following functionalities to address the issue:

Weapon Interaction System: Players can now pick up weapons from the environment and add them to their inventory.

Inventory Integration: Weapons can be equipped from the inventory, dropped back into the environment, and correctly placed in the player’s hands when equipped.

Animation Rigging Integration: Ensures seamless placement of weapons in the player's hands using Unity's Animation Rigging package for IK.

How It Works

1.⁠ ⁠Weapon Setup:

Add the Weapon Manager script to a new weapon prefab.

Attach two colliders:

A Box Collider (set as a trigger) for interaction.

A Mesh Collider (not a trigger) to define the weapon's physical shape.

Add a Rigidbody component for physics interactions.

2.⁠ ⁠Player Setup:

Add the Weapon Handler script to the player’s parent object.

Create three Animation Rigging objects:

Hand IKs for controlling the player’s hands.

Weapon Object IKs for positioning the weapon correctly in the hands.

Refer to the setup in Crafter@RightFist > Character_Robot_01 in the DemoPrincipalScene for a working example.

### CODE REVIEW

**Comment by od-hunter** [comment]
Hi @sebas11042 please review, fixed conflicts

**Review by Josue19-08 — CHANGES_REQUESTED** [review]
I think you have modified files that you should not have edited, please correct them, make sure you only edit what you should modify.

**Comment by od-hunter** [comment]
> I think you have modified files that you should not have edited, please correct them, make sure you only edit what you should modify.

Hello @Josue19-08 , I think I left print statements I forgot to clear, i didn't adjust any lines of code

**Comment by od-hunter** [comment]
I used unity 6 initially cause I didn't have stable network to download unity 2022 editor, then I switched back to 2022 version to make the commit. @Josue19-08

**Comment by od-hunter** [comment]
@Josue19-08 , please review and merge.

**Comment by Josue19-08** [comment]
@od-hunter There is an issue with your PR when using Unity 6, compatibility with our project was affected when testing and running. I understand that was the version you had at the time but we would not be able to merge those changes if you used Unity in development.

**Review by Josue19-08 — CHANGES_REQUESTED** [review]
It is not possible to make you merge something that is not functional with our version of Unty

**Pull request closed without merging**
