### PR TITLE
Feat: Enemy NPC Reaction to the Main Character

### PR DESCRIPTION
**Pull request by ShantelPeters**
- Adds Enemy NPC to scene with a proper Animator Controller and Idle State Animation
- Adds base framework for Enemy NPC interaction (Detecting, Chasing & Attacking the Player)
- Adds NavMesh to the DemoPrincipal Scene for AI navigation
- Creates an Animator Controller for the Enemy NPC

Extras
- Adds ```.gitignore``` file to the Unity directory

### CODE REVIEW

**Comment by CristopherAguilar10** [comment]
in a few moments we will review 🚀

**Comment by Josue19-08** [comment]
@ShantelPeters Great work on the attack animation! To enhance it further, I would like the NPC to adjust its movement to follow the main character's direction as they approach. Think of it as a dynamic "cat and mouse" interaction, where the NPC actively reacts to the main character's movements.

The video shows an NPC walking in a straight line without adjusting his movement based on the main character. Unlike a dynamic interaction, the NPC does not follow or react to the player, leading them to attack each other if they encounter an obstacle.

https://www.loom.com/share/ac743d82e74f42eda363ae5d1a5e4675?sid=73607808-c0f8-488c-80c1-19c84af9ad37

**Review by Josue19-08 — COMMENTED** [review]
@ShantelPeters Great work on the attack animation! To enhance it further, I would like the NPC to adjust its movement to follow the main character's direction as they approach. Think of it as a dynamic "cat and mouse" interaction, where the NPC actively reacts to the main character's movements.

The video shows an NPC walking in a straight line without adjusting his movement based on the main character. Unlike a dynamic interaction, the NPC does not follow or react to the player, leading them to attack each other if they encounter an obstacle.

https://www.loom.com/share/ac743d82e74f42eda363ae5d1a5e4675?sid=73607808-c0f8-488c-80c1-19c84af9ad37

**Comment by ShantelPeters** [comment]
@Josue19-08 Thank you
Noted, I'll get started on that. In essence, the enemy NPC should face the player when attacking yeah?

From the video, I think the attack and tracking range need to be adjusted properly too. I have to tinker with it for a bit to find the sweet spot

**Review by Josue19-08 — APPROVED** [review]
LGTM! :)

**Review by sebas11042 — APPROVED** [review]

**Review by CristopherAguilar10 — APPROVED** [review]

**Pull request merged**
